# Pilot/Flying-J
workdir: 'pfj'
baseurl: 'https://locations.pilotflyingj.com'
searchurl: '{{ baseurl }}/search'

jobs:
  # Load the search page and extract codes for search options to use in main search
  - what: "search page to find search options"
    url: '{{ searchurl }}?r=50&l=en'
    # file: null
    # ready: null
    extract:
      operation: attribute
      into: amenity
      xpath: '//input[@data-ya-track="electric-vehicle-charging-station"]'
      attribute: 'value'
      what: 'amenity code for electric vehicle charging stations'
  # Now do the main search, iterating through all the countries and regions within those countries, extracting store URLs
  - what: "search results for {{ state.long_name }}, {{ country.long_name }}"
    url: "{{ searchurl }}?locations=all&r=50&amenity={{ amenity }}&l=en"
    file: "{{ workdir }}/all-locations.html"
    ready: '//div[contains(@class, "Locator-resultsSummary")]'
    extract:
      operation: attributes
      xpath: '//a[@class="Teaser-titleLink"]'
      attribute: 'href'
      into: urls
  # Now fetch the store detail pages and extract the interesting data into an array
  - what: 'store details'
    url: "https://locations.pilotflyingj.com/{{ url|raw }}"
    file: "{{ workdir }}/{{ url|replace({'/': '-'})|raw }}.html"
    data:
      urls
    keys:
      - name: url
        key: urls
    extract:
      operation: items
      into: details
      items:
        name: '//h1[@itemprop="name"]/text()[following-sibling::br[1]]'
        price: '//div[contains(@class, "EvCharger-priceDetail")]'
        address: '//a//span[contains(@class, "c-address-street-1")]'
        city: '//a//span[contains(@class, "c-address-city")]'
        state: '//a//abbr[contains(@class, "c-address-state")]'
        zip: '//a//span[contains(@class, "c-address-postal-code")]'
        country: '//a//abbr[contains(@class, "c-address-country-name")]'
        chargers:
          base: '//div[contains(@class, "EvCharger-Cardinfo")]'
          fields:
            model: './p[contains(@class, "EvCharger-model")]'
            type: './div[contains(@class, "EvCharger-powerinfo")]/span[1]'
            power: './div[contains(@class, "EvCharger-powerinfo")]/span[2]'
  # Finished.  Now output the data we captured
  - what: 'output'
    extract:
      operation: output
      output: php://output
      format: csv
      from: details
