# Pilot/Flying-J
#
# Downloads EV charging data from the Pilot/Flying-J web site and outputs it as CSV
# Requires a working directory called 'pfj' to store the CSV and copies of downloaded files 
#
workdir: 'pfj'
baseurl: 'https://locations.pilotflyingj.com'
searchurl: '{{ baseurl }}/search'

jobs:
  - operation: message
    message: "Starting scraping of Pilot/Flying-J locations"
  # Load the search page and extract codes for search options to use in main search
  - operation: attribute
    what: "search page to find search options"
    url: '{{ searchurl }}?r=50&l=en'
    # file: null
    # ready: null
    extract:
      into: amenity
      xpath: '//input[@data-ya-track="electric-vehicle-charging-station"]'
      attribute: 'value'
      what: 'amenity code for electric vehicle charging stations'
  # Now do the main search, iterating through all the countries and regions within those countries, extracting store URLs
  - operation: attributes
    what: "search results for all EV charging locations"
    url: "{{ searchurl }}?locations=all&r=50&amenity={{ amenity }}&l=en"
    file: "{{ workdir }}/all-locations.html"
    ready: '//div[contains(@class, "Locator-resultsSummary")]'
    extract:
      xpath: '//a[@class="Teaser-titleLink"]'
      attribute: 'href'
      into: urls
  # Sort the URLs
  - operation: sort
    into: urls
  # Now fetch the store detail pages and extract the interesting data into an array
  - operation: items
    what: 'store details'
    url: "{{ baseurl }}/{{ url|raw }}"
    file: "{{ workdir }}/{{ url|replace({'/': '-'})|raw }}.html"
    data:
      urls
    keys:
      - name: url
        key: urls
    extract:
      into: details
      items:
        name: '//h1[@itemprop="name"]/text()[following-sibling::br[1]]'
        price: '//div[contains(@class, "EvCharger-priceDetail")]'
        address: '//a//span[contains(@class, "c-address-street-1")]'
        city: '//a//span[contains(@class, "c-address-city")]'
        state: '//a//abbr[contains(@class, "c-address-state")]'
        zip: '//a//span[contains(@class, "c-address-postal-code")]'
        country: '//a//abbr[contains(@class, "c-address-country-name")]'
        latitude: '//div[contains(@class, "About-map")]//meta[@itemprop="latitude"]/@content'
        longitude: '//div[contains(@class, "About-map")]//meta[@itemprop="longitude"]/@content'
        chargers:
          base: '//div[contains(@class, "EvCharger-Cardinfo")]'
          fields:
            model: './p[contains(@class, "EvCharger-model")]'
            type: './div[contains(@class, "EvCharger-powerinfo")]/span[1]'
            power: './div[contains(@class, "EvCharger-powerinfo")]/span[2]'
  # Finished.  Now output the data we captured
  - operation: output
    what: 'output'
    from: details
    extract:
      output: php://output
      format: csv
  - operation: message
    message: "Scraping of Pilot/Flying-J locations complete"
